#!/bin/bash
#SBATCH -J BWAT-29C
#SBATCH -p sgpu
#SBATCH --qos Normal
#SBATCH -t 24:00:00
#SBATCH -N 1
#SBATCH --output=T-29C-S3-S8.out

module load jdk

#2019-05-15
#OsteosarcomaWES

#S3_Running BWA --- T-29C

bwa mem -M -t 12 \
-R '@RG\tID:@A00405\tSM:T-29C\tPL:illumina\tLB:lib4\tPU:T-29C.ATCATTCC.1' \
/projects/sdas@colostate.edu/CanFamDatabases/DogGenome/CanFam3 \
../Trimfiles/T29C_R1_paired.fastq.gz \
../Trimfiles/T29C_R2_paired.fastq.gz > ../sam/T-29C_BWA.sam


#S4_Sort SAM for marking duplicates --- T-29C

java -jar ~/picard.jar SortSam \
      TMP_DIR=../bam/tempT-29C \
      I=../sam/T-29C_BWA.sam \
      O=../sam/T-29C_BWA_sorted.sam \
      SORT_ORDER=coordinate

#S4a_Removing the unsorted sam file

rm ../sam/T-29C_BWA.sam

#S5_Mark Duplicates --- T-29C 

java -jar ~/picard.jar MarkDuplicates \
 	TMP_DIR=../bam/tempT-29C \
 	I=../sam/T-29C_BWA_sorted.sam \
 	O=../bam/T-29C_dedup.bam \
 	M=../bam/T-29C_marked_dup_metrics.txt

#S6_Index bam file --- T-29C

samtools index ../bam/T-29C_dedup.bam

#S7_Recalibrate Base --- T-29C

gatk BaseRecalibrator \
   -R /projects/sdas\@colostate.edu/CanFamDatabases/DogGenome/Canis_familiaris.CanFam3.1.dna.fa  \
   -I ../bam/T-29C_dedup.bam \
   --known-sites /projects/sdas\@colostate.edu/CanFamDatabases/Canis_familiaris_V89.vcf \
   -O ../bam/T-29C_recal_data.grp

#S8_Print bam file with recalibrated bases --- T-29C

gatk ApplyBQSR \
   -R /projects/sdas\@colostate.edu/CanFamDatabases/DogGenome/Canis_familiaris.CanFam3.1.dna.fa \
   -I ../bam/T-29C_dedup.bam \
   --bqsr-recal-file  ../bam/T-29C_recal_data.grp \
   -O ../BAM/T-29C_recal_reads.bam

